# Nom du projet
site_name: Nom de votre projet

# URL de base (optionnel pour Read the Docs)
# site_url: https://votredocumentation.readthedocs.io

# Thème utilisé (par défaut "readthedocs")
theme:
  name: material
  features:
    - navigation.tabs

# Répertoire contenant les fichiers Markdown
docs_dir: docs

# Configuration des pages de la documentation
nav:
  - Accueil: index.md


# Extensions Markdown
markdown_extensions:
  - tables
  
# Plugins



# Fichiers statiques (optionnel)
# extra_css:
#   - styles/extra.css
# extra_javascript:
#   - scripts/extra.js
